package com.upstart.service.application.entity;
// Generated Sep 18, 2021 7:24:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "chootay_bikes")
public class Customer implements java.io.Serializable
{

	private Integer id;
	private String name;
	private String address;
	private Date createdTimestamp;
	@JsonIgnore
	private Set<RepairBike> repairBikes = new HashSet<RepairBike>(0);

	public Customer()
	{
	}

	public Customer(String name, String address, Date createdTimestamp)
	{
		this.name = name;
		this.address = address;
		this.createdTimestamp = createdTimestamp;
	}

	public Customer(String name, String address, Date createdTimestamp, Set<RepairBike> repairBikes)
	{
		this.name = name;
		this.address = address;
		this.createdTimestamp = createdTimestamp;
		this.repairBikes = repairBikes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "address", nullable = false, length = 500)
	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 19)
	public Date getCreatedTimestamp()
	{
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp)
	{
		this.createdTimestamp = createdTimestamp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<RepairBike> getRepairBikes()
	{
		return this.repairBikes;
	}

	public void setRepairBikes(Set<RepairBike> repairBikes)
	{
		this.repairBikes = repairBikes;
	}

}
