package com.upstart.service.application.entity;
// Generated Sep 18, 2021 7:24:22 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SparePartToRepairBike generated by hbm2java
 */
@Entity
@Table(name = "spare_part_to_repair_bike", catalog = "chootay_bikes")
public class SparePartToRepairBike implements java.io.Serializable
{

	private Integer id;
	@JsonIgnore
	private RepairBike repairBike;
	private SparePart sparePart;
	private int quantity;
	private Date createdTimestamp;

	public SparePartToRepairBike()
	{
	}

	public SparePartToRepairBike(RepairBike repairBike, SparePart sparePart, int quantity, Date createdTimestamp)
	{
		this.repairBike = repairBike;
		this.sparePart = sparePart;
		this.quantity = quantity;
		this.createdTimestamp = createdTimestamp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bike_id", nullable = false)
	public RepairBike getRepairBike()
	{
		return this.repairBike;
	}

	public void setRepairBike(RepairBike repairBike)
	{
		this.repairBike = repairBike;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spare_parts_id", nullable = false)
	public SparePart getSparePart()
	{
		return this.sparePart;
	}

	public void setSparePart(SparePart sparePart)
	{
		this.sparePart = sparePart;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity()
	{
		return this.quantity;
	}

	public void setQuantity(int quantity)
	{
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_timestamp", nullable = false, length = 19)
	public Date getCreatedTimestamp()
	{
		return this.createdTimestamp;
	}

	public void setCreatedTimestamp(Date createdTimestamp)
	{
		this.createdTimestamp = createdTimestamp;
	}

}
